## 01a Experiment 1a: Category Membership - Items Task

### 0 Setup

In [1]:
import pandas as pd
import csv
from google import genai
from google.genai import types
import time
import random

### 1 Functions

In [2]:
# Prompt Model to answer Questionnaire

def collect_output(client, prompt):
    response = client.models.generate_content(
        model="gemini-3-pro-preview",
        contents=prompt)
    return response

### A. Items Task

In [3]:
# CATEGORIES
categories = ["Fruit","Vehicle","Weapon","Vegetable", "Carpenter's tool", "Bird", "Sport", "Toy", "Clothing"] #from rosch1975a

# + "Furniture" category, but "furniture" excluded here, because using results from prompts experiment with prompt 6

In [ ]:
# Collect Answers from Model

items_reps = 5 #30

# retrieve API 
with open('', 'r') as file:
    api = file.read()     
client = genai.Client(api_key=api)

prompt_outputs = pd.DataFrame(columns=['model', 'prompt', 'prompt_id', 'runtime', 'category', 'output'])
model_output = pd.DataFrame()

for rep in range(items_reps): # max rep == 30

        rep_categories = categories.copy() 
        random.shuffle(rep_categories)
        
        for i in range(len(rep_categories)):

            current_prompt = f"""
            The procedure will be as follows: First you will be given the name or description of a category. Then you will write as many items included in that category as you can, in whatever order they happen to occur to you. The category is: "{rep_categories[i]}".
            Do not add any further details, only write the items that answer the instruction.
            Provide your answer in plain text as a comma-separated list of nouns.
            """
            
            start_time = time.time() 
            output = collect_output(client, current_prompt)
            end_time = time.time() 
            runtime = end_time - start_time
            model_output = pd.DataFrame({
                'model': 'gemini-3-pro',
                'prompt': [current_prompt],
                'prompt_id': [6],
                'runtime': [runtime],
                'category': [rep_categories[i]],
                'output': [output]
            })
            
            prompt_outputs = pd.concat([prompt_outputs, model_output], ignore_index=True)

prompt_outputs.head()

C:\Users\AS\AppData\Local\Temp\ipykernel_16256\3635328170.py:39: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  prompt_outputs = pd.concat([prompt_outputs, model_output], ignore_index=True)

,model,prompt,prompt_id,runtime,category,output
0,gemini-3-pro,\n The procedure will be as follows...,6,87.558914,Vehicle,sdk_http_response=HttpResponse(\n headers=<di...
1,gemini-3-pro,\n The procedure will be as follows...,6,67.749557,Weapon,sdk_http_response=HttpResponse(\n headers=<di...
2,gemini-3-pro,\n The procedure will be as follows...,6,64.604481,Toy,sdk_http_response=HttpResponse(\n headers=<di...
3,gemini-3-pro,\n The procedure will be as follows...,6,64.333744,Fruit,sdk_http_response=HttpResponse(\n headers=<di...
4,gemini-3-pro,\n The procedure will be as follows...,6,79.516820,Bird,sdk_http_response=HttpResponse(\n headers=<di...

In [10]:
prompt_outputs

,model,prompt,prompt_id,runtime,category,output
0,gemini-3-pro,\n The procedure will be as follows...,6,87.558914,Vehicle,"car, truck, bus, bicycle, motorcycle, van, sco..."
1,gemini-3-pro,\n The procedure will be as follows...,6,67.749557,Weapon,"sword, knife, gun, pistol, rifle, shotgun, dag..."
2,gemini-3-pro,\n The procedure will be as follows...,6,64.604481,Toy,"doll, action figure, teddy bear, stuffed anima..."
3,gemini-3-pro,\n The procedure will be as follows...,6,64.333744,Fruit,"apple, banana, orange, pear, grape, strawberry..."
4,gemini-3-pro,\n The procedure will be as follows...,6,79.516820,Bird,"robin, sparrow, eagle, hawk, owl, penguin, ost..."
5,gemini-3-pro,\n The procedure will be as follows...,6,48.091189,Sport,"soccer, basketball, tennis, baseball, american..."
6,gemini-3-pro,\n The procedure will be as follows...,6,49.131781,Carpenter's tool,"Hammer, saw, drill, tape measure, chisel, plan..."
7,gemini-3-pro,\n The procedure will be as follows...,6,47.765399,Clothing,"shirt, pants, dress, skirt, shorts, socks, sho..."
8,gemini-3-pro,\n The procedure will be as follows...,6,38.017884,Vegetable,"Carrot, potato, broccoli, cauliflower, spinach..."
9,gemini-3-pro,\n The procedure will be as follows...,6,73.123747,Clothing,"shirt, pants, dress, skirt, blouse, sweater, j..."
10,gemini-3-pro,\n The procedure will be as follows...,6,25.669895,Toy,"doll, ball, car, truck, train, plane, blocks, ..."
11,gemini-3-pro,\n The procedure will be as follows...,6,33.737353,Weapon,"gun, sword, knife, spear, bomb, rifle, pistol,..."
12,gemini-3-pro,\n The procedure will be as follows...,6,43.474612,Vehicle,"car, truck, bus, van, motorcycle, bicycle, air..."
13,gemini-3-pro,\n The procedure will be as follows...,6,52.204277,Vegetable,"carrot, potato, broccoli, spinach, lettuce, to..."
14,gemini-3-pro,\n The procedure will be as follows...,6,39.298004,Fruit,"apple, banana, orange, pear, grape, strawberry..."
15,gemini-3-pro,\n The procedure will be as follows...,6,63.960604,Carpenter's tool,"hammer, hand saw, tape measure, level, chisel,..."
16,gemini-3-pro,\n The procedure will be as follows...,6,69.984738,Bird,"robin, sparrow, eagle, hawk, pigeon, crow, rav..."
17,gemini-3-pro,\n The procedure will be as follows...,6,24.290094,Sport,"soccer, basketball, tennis, baseball, football..."
18,gemini-3-pro,\n The procedure will be as follows...,6,76.734257,Sport,"football, basketball, baseball, soccer, tennis..."
19,gemini-3-pro,\n The procedure will be as follows...,6,29.102322,Bird,"Sparrow, robin, eagle, hawk, pigeon, crow, rav..."
20,gemini-3-pro,\n The procedure will be as follows...,6,38.008391,Carpenter's tool,"hammer, saw, tape measure, chisel, screwdriver..."
21,gemini-3-pro,\n The procedure will be as follows...,6,26.664704,Vegetable,"carrot, potato, onion, garlic, tomato, cucumbe..."
22,gemini-3-pro,\n The procedure will be as follows...,6,64.565951,Fruit,"apple, banana, orange, grape, strawberry, blue..."
23,gemini-3-pro,\n The procedure will be as follows...,6,68.610870,Weapon,"gun, sword, knife, pistol, rifle, shotgun, bom..."
24,gemini-3-pro,\n The procedure will be as follows...,6,25.427488,Vehicle,"car, truck, bus, van, motorcycle, bicycle, sco..."
25,gemini-3-pro,\n The procedure will be as follows...,6,57.484414,Clothing,"shirt, pants, dress, skirt, shorts, sweater, j..."
26,gemini-3-pro,\n The procedure will be as follows...,6,97.128717,Toy,"doll, action figure, teddy bear, stuffed anima..."
27,gemini-3-pro,\n The procedure will be as follows...,6,25.493876,Vehicle,"Car, truck, bus, van, motorcycle, bicycle, sco..."
28,gemini-3-pro,\n The procedure will be as follows...,6,65.721733,Clothing,"shirt, pants, dress, skirt, shorts, jeans, t-s..."
29,gemini-3-pro,\n The procedure will be as follows...,6,35.403144,Weapon,"gun, pistol, rifle, shotgun, revolver, machine..."
30,gemini-3-pro,\n The procedure will be as follows...,6,120.581127,Toy,"doll, action figure, teddy bear, stuffed anima..."
31,gemini-3-pro,\n The procedure will be as follows...,6,25.419466,Bird,"robin, sparrow, eagle, hawk, pigeon, crow, rav..."
32,gemini-3-pro,\n The procedure will be as follows...,6,52.991695,Sport,"Soccer, basketball, tennis, baseball, cricket,..."
33,gemini-3-pro,\n The procedure will be as follows...,6,99.276793,Carpenter's tool,"hammer, saw, tape measure, level, chisel, scre..."
34,gemini-3-pro,\n The procedure will be as follows...,6,123.282828,Fruit,"apple, banana, orange, grape, strawberry, blue..."
35,gemini-3-pro,\n The procedure will be as follows...,6,117.810611,Vegetable,"carrot, potato, onion, broccoli, spinach, lett..."
36,gemini-3-pro,\n The procedure will be as follows...,6,119.266509,Vehicle,"car, truck, bus, van, bicycle, motorcycle, sco..."
37,gemini-3-pro,\n The procedure will be as follows...,6,24.942117,Toy,"doll, action figure, teddy bear, stuffed anima..."
38,gemini-3-pro,\n The procedure will be as follows...,6,114.373725,Fruit,"apple, pear, orange, banana, grape, strawberry..."
39,gemini-3-pro,\n The procedure will be as follows...,6,111.463792,Bird,"eagle, hawk, falcon, owl, sparrow, robin, card..."
40,gemini-3-pro,\n The procedure will be as follows...,6,111.671248,Sport,"football, soccer, basketball, baseball, tennis..."
41,gemini-3-pro,\n The procedure will be as follows...,6,28.899390,Weapon,"sword, gun, knife, spear, bow, arrow, pistol, ..."
42,gemini-3-pro,\n The procedure will be as follows...,6,17.734456,Carpenter's tool,"hammer, tape measure, level, chisel, speed squ..."
43,gemini-3-pro,\n The procedure will be as follows...,6,128.505481,Clothing,"shirt, t-shirt, blouse, sweater, sweatshirt, h..."
44,gemini-3-pro,\n The procedure will be as follows...,6,105.493294,Vegetable,"carrot, potato, broccoli, cauliflower, spinach..."

In [ ]:
# Cleaning Model Output

text = ""
response = prompt_outputs['output'][0]

def extract_text(row):
    text = ""
    for candidate in row['output'].candidates:
        for part in candidate.content.parts:
            text += part.text + "\n"  
    return text.strip()  

prompt_outputs['output'] = prompt_outputs.apply(extract_text, axis=1)

In [12]:
prompt_outputs.head()

,model,prompt,prompt_id,runtime,category,output
0,gemini-3-pro,\n The procedure will be as follows...,6,87.558914,Vehicle,"car, truck, bus, bicycle, motorcycle, van, sco..."
1,gemini-3-pro,\n The procedure will be as follows...,6,67.749557,Weapon,"sword, knife, gun, pistol, rifle, shotgun, dag..."
2,gemini-3-pro,\n The procedure will be as follows...,6,64.604481,Toy,"doll, action figure, teddy bear, stuffed anima..."
3,gemini-3-pro,\n The procedure will be as follows...,6,64.333744,Fruit,"apple, banana, orange, pear, grape, strawberry..."
4,gemini-3-pro,\n The procedure will be as follows...,6,79.516820,Bird,"robin, sparrow, eagle, hawk, owl, penguin, ost..."

In [13]:
len(prompt_outputs)

45

In [14]:
# take away NaN Answers
print("Number of rows:", len(prompt_outputs),"\n")
prompt_outputs.dropna(inplace=True)
print("Number of rows after NA filtering:", len(prompt_outputs))

Number of rows: 45

Number of rows after NA filtering: 45

In [15]:
prompt_outputs.to_csv(f'01_catmemexp_itemstask_allmodels_raw.csv',index=False, quoting=csv.QUOTE_ALL, encoding='utf-8', mode='a')