## Property 3: Graded Membership

In [1]:
# Setup
import pandas as pd
import csv
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import ast
import numpy as np
from collections import defaultdict
from matplotlib.ticker import MaxNLocator

In [7]:
# Import Data

attributes_df  = pd.read_csv('01_catmemexp_attributestask_allmodels_processed.csv', dtype=str, quoting=csv.QUOTE_ALL, encoding = "utf-8")
attributes_df['output_list_processed_nonoise'] = attributes_df['output_list_processed_nonoise'].apply(ast.literal_eval)

items_df = pd.read_csv('01_catmemexp_itemstask_allmodels_processed.csv', dtype=str, quoting=csv.QUOTE_ALL, encoding="utf-8")
items_df['output_list_processed_nonoise'] = items_df['output_list_processed_nonoise'].apply(ast.literal_eval)


unique_attributes_df  = pd.read_csv('famres_scores_df.csv')
unique_attributes_df.head()

,model,category,item,attributes,attribute_scores,basic_measure,log_measure,frequency
0,Qwen2.5-7B-Instruct,Furniture,armchair,"['comfortable', 'wooden', 'upholstered', 'armr...","[np.int64(6), np.int64(13), np.int64(4), np.in...",44,12.727720,22
1,Qwen2.5-7B-Instruct,Furniture,bookshelf,"['tall', 'sturdy', 'furniture', 'rectangular',...","[np.int64(2), np.int64(6), np.int64(5), np.int...",52,12.727720,29
2,Qwen2.5-7B-Instruct,Furniture,bunk bed,"['supportive', 'tiered', 'wooden', 'bunk', 'be...","[np.int64(2), np.int64(1), np.int64(13), np.in...",28,5.455321,9
3,Qwen2.5-7B-Instruct,Furniture,cabinet,"['furniture', 'rectangular', 'cabinetry', 'she...","[np.int64(5), np.int64(9), np.int64(2), np.int...",46,11.341425,8
4,Qwen2.5-7B-Instruct,Furniture,chair,"['supportive', 'comfortable', 'sturdy', 'seate...","[np.int64(2), np.int64(6), np.int64(6), np.int...",54,15.079095,30

In [ ]:
unique_models = unique_attributes_df['model'].unique()

model_dataframes = {}

for model in unique_models:

    unique_categories = unique_attributes_df[unique_attributes_df['model'] == model]['category'].unique()

    common_attributes_counts = {}

    for category in unique_categories:

        filtered_df = unique_attributes_df[
            (unique_attributes_df['model'] == model) & 
            (unique_attributes_df['category'] == category)
        ]

        sorted_df = filtered_df.sort_values(by='frequency')

        most_frequent_items = sorted_df.tail(5)
        least_frequent_items = sorted_df.head(5)

        most_frequent_items['attributes'] = most_frequent_items['attributes'].apply(eval)
        least_frequent_items['attributes'] = least_frequent_items['attributes'].apply(eval)

        most_common_attributes = set(most_frequent_items['attributes'].iloc[0])  
        for attrs in most_frequent_items['attributes'].iloc[1:]:
            most_common_attributes.intersection_update(attrs)

        most_common_count = len(most_common_attributes)

        least_common_attributes = set(least_frequent_items['attributes'].iloc[0])  
        for attrs in least_frequent_items['attributes'].iloc[1:]:
            least_common_attributes.intersection_update(attrs)

        least_common_count = len(least_common_attributes)

        common_attributes_counts[category] = {
            'Category': category,
            'Model': model,
            'Most typical members': most_common_count,
            'Least typical members': least_common_count,
        }

    model_summary_df = pd.DataFrame.from_dict(common_attributes_counts, orient='index')

    model_dataframes[model] = model_summary_df

concatenated_df = pd.concat(model_dataframes.values(), ignore_index=True)

concatenated_df.to_csv('combined_freq_attr_summary.csv', index=False)

print("\nCombined Summary DataFrame:")
concatenated_df

Combined Summary DataFrame:

C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  most_frequent_items['attributes'] = most_frequent_items['attributes'].apply(eval)
C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  least_frequent_items['attributes'] = least_frequent_items['attributes'].apply(eval)
C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  most_frequent_items['attributes'] = most_frequent_items['attributes'].apply(eval)
C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  least_frequent_items['attributes'] = least_frequent_items['attributes'].apply(eval)
C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  most_frequent_items['attributes'] = most_frequent_items['attributes'].apply(eval)
C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  least_frequent_items['attributes'] = least_frequent_items['attributes'].apply(eval)
C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  most_frequent_items['attributes'] = most_frequent_items['attributes'].apply(eval)
C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  least_frequent_items['attributes'] = least_frequent_items['attributes'].apply(eval)
C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  most_frequent_items['attributes'] = most_frequent_items['attributes'].apply(eval)
C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  least_frequent_items['attributes'] = least_frequent_items['attributes'].apply(eval)
C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  most_frequent_items['attributes'] = most_frequent_items['attributes'].apply(eval)
C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  least_frequent_items['attributes'] = least_frequent_items['attributes'].apply(eval)
C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  most_frequent_items['attributes'] = most_frequent_items['attributes'].apply(eval)
C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  least_frequent_items['attributes'] = least_frequent_items['attributes'].apply(eval)
C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  most_frequent_items['attributes'] = most_frequent_items['attributes'].apply(eval)
C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  least_frequent_items['attributes'] = least_frequent_items['attributes'].apply(eval)
C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  most_frequent_items['attributes'] = most_frequent_items['attributes'].apply(eval)
C:\Users\AS\AppData\Local\Temp\ipykernel_26196\1799504273.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  least_frequent_items['attributes'] = least_frequent_items['attributes'].apply(eval)

,Category,Model,Most typical members,Least typical members
0,Furniture,Qwen2.5-7B-Instruct,0,0
1,Vehicle,Qwen2.5-7B-Instruct,0,0
2,Vegetable,Qwen2.5-7B-Instruct,1,0
3,Weapon,Qwen2.5-7B-Instruct,0,0
4,Fruit,Qwen2.5-7B-Instruct,1,0
5,Clothing,Qwen2.5-7B-Instruct,0,0
6,Furniture,Qwen2.5-14B-Instruct,2,3
7,Vehicle,Qwen2.5-14B-Instruct,0,0
8,Vegetable,Qwen2.5-14B-Instruct,0,1
9,Weapon,Qwen2.5-14B-Instruct,1,0
10,Fruit,Qwen2.5-14B-Instruct,1,0
11,Clothing,Qwen2.5-14B-Instruct,0,0
12,Furniture,Qwen2.5-32B-Instruct,0,1
13,Vehicle,Qwen2.5-32B-Instruct,0,0
14,Vegetable,Qwen2.5-32B-Instruct,3,3
15,Weapon,Qwen2.5-32B-Instruct,0,0
16,Fruit,Qwen2.5-32B-Instruct,1,0
17,Clothing,Qwen2.5-32B-Instruct,0,0
18,Furniture,Qwen2.5-72B-Instruct,3,1
19,Vehicle,Qwen2.5-72B-Instruct,2,0
20,Vegetable,Qwen2.5-72B-Instruct,2,1
21,Weapon,Qwen2.5-72B-Instruct,3,0
22,Fruit,Qwen2.5-72B-Instruct,0,1
23,Clothing,Qwen2.5-72B-Instruct,2,1
24,Furniture,Meta-Llama-3.1-8B-Instruct,1,0
25,Vehicle,Meta-Llama-3.1-8B-Instruct,0,0
26,Vegetable,Meta-Llama-3.1-8B-Instruct,3,2
27,Weapon,Meta-Llama-3.1-8B-Instruct,0,0
28,Fruit,Meta-Llama-3.1-8B-Instruct,4,5
29,Clothing,Meta-Llama-3.1-8B-Instruct,0,0
30,Furniture,Meta-Llama-3.1-70B-Instruct,1,0
31,Vehicle,Meta-Llama-3.1-70B-Instruct,0,2
32,Vegetable,Meta-Llama-3.1-70B-Instruct,2,3
33,Weapon,Meta-Llama-3.1-70B-Instruct,1,0
34,Fruit,Meta-Llama-3.1-70B-Instruct,2,0
35,Clothing,Meta-Llama-3.1-70B-Instruct,0,0
36,Furniture,gemini-3-pro,3,0
37,Vehicle,gemini-3-pro,2,0
38,Vegetable,gemini-3-pro,4,2
39,Weapon,gemini-3-pro,1,1
40,Fruit,gemini-3-pro,4,1
41,Clothing,gemini-3-pro,2,0
42,Furniture,gpt-5.2,17,16
43,Vehicle,gpt-5.2,3,0
44,Vegetable,gpt-5.2,5,5
45,Weapon,gpt-5.2,1,1
46,Fruit,gpt-5.2,12,4
47,Clothing,gpt-5.2,9,5
48,Furniture,deepseek-chat,3,2
49,Vehicle,deepseek-chat,0,0
50,Vegetable,deepseek-chat,2,2
51,Weapon,deepseek-chat,0,0
52,Fruit,deepseek-chat,5,2
53,Clothing,deepseek-chat,2,0